version: 0.0
os: linux
files:
  - source: target/SimpleApiSample-0.0.1-SNAPSHOT.jar
    destination: /var/SimpleApiSample/
  - source: deploy/SimpleApiSample.service
    destination: /etc/systemd/system/
hooks:
  ApplicationStop:
    - location: deploy/stopapp.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy/startapp.sh
      timeout: 300
      runas: root