version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in this phase
  build:
    commands:
      - echo Build started on `date`
      - mvn package -DskipTests=true
  post_build:
    commands:
      - echo Nothing to do in this phase
artifacts:
  files:
    - target/SimpleApiSample-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - deploy/*
cache:
  paths:
    - '/root/.m2/**/*'